@startuml

actor "Client A" as CA
entity "Server Handler A" as SVA
entity "Client A Receiver" as CAR
entity "Client B" as CB
entity "Server Handler B" as SVB
entity "Client B Receiver" as CBR

activate CA
activate SVA
activate CAR
activate CB
activate SVB
activate CBR

CA -> CA : Wait for \ninput
CAR -> CAR : Wait for \na message

CB -> CB : Wait for \ninput
CBR -> CBR : Wait for \nmessage


CA -> SVA : Send message
deactivate CA

SVA -> SVA : Controll  \nmessage type
SVA -> CBR : Send message

activate CA
CA -> CA : Wait for \ninput

CBR -> CBR : Outprint \nmessage
deactivate CBR

CB -> SVB : Send message
deactivate CB
activate CBR
CBR -> CBR : Wait for \nmessage

SVB -> SVB : Controll \nmessage type
SVB -> CAR : Send message

activate CB
CB -> CB : Wait for \ninput

CAR -> CAR : Outprint \nmessage
deactivate CAR


@enduml