@startuml


entity Server
actor "Client A" as CA
entity "Server Handler A" as SVA
entity "Client A Receiver" as CAR
entity "Client B" as CB
entity "Server Handler B" as SVB
entity "Client B Receiver" as CBR

 == all threads waiting  ==


CA -> SVA : Send message
CA -> CA : Wait for \ninput

Server -> SVA : Send messageHandler
Server -> SVA : Send connected clients

SVA -> SVA : Controll  \nmessage type
SVA -> CBR : Send message


CBR -> CBR : Outprint \nmessage
CBR -> CBR : Wait for \nmessage

CB -> SVB : Send message
CB -> CB : Wait for input

Server -> SVB : Send messageHandler
Server -> SVB : Send connected clients

SVB -> SVB : Controll \nmessage type
SVB -> CAR : Send message

CAR -> CAR : Outprint \nmessage
CAR -> CAR : Wait for message

@enduml