@startuml
'https://plantuml.com/class-diagram

+class ThrowDice {
ArrayList dices();
amountofThrows();
amountofDices();

}

-enum WinPatterns {

1 - 6 Augen zähler;
Bonus bei Gesamt 63 Points;
DreierPasch;
ViererPasch;
Full-House;
Kleine-Straße;
Große-Straße;
Kniffel;
Chance;

}
@enduml

